CREATE TABLE IF NOT EXISTS anime(
  id INTEGER PRIMARY KEY,
  mal_id INTEGER DEFAULT 0,
  kitsu_id INTEGER DEFAULT 0,
  anilist_id INTEGER DEFAULT 0,
  title TEXT,
  english TEXT,
  japanese TEXT,
  synonym TEXT,
  type INTEGER,
  status INTEGER,
  episode_count INTEGER,
  episode_length INTEGER,
  date_start TEXT,
  date_end TEXT,
  image TEXT,
  trailer_id TEXT,
  age_rating INTEGER,
  genres TEXT,
  tags TEXT,
  producers TEXT,
  studios TEXT,
  score TEXT,
  popularity INTEGER,
  synopsis TEXT,
  last_aired_episode INTEGER,
  next_episode_time TEXT,
  modified TEXT
);
